### ISSUE TITLE
Cannot take effect on LG ultrafine 4k 23.7 inch.

### ISSUE THREAD

**Issue by zdaxie** [Willian-Zhang/LG-Ultrafine-Brightness-2#5]
Is there any setting or code should I change to make it work on LG ultrafine 4k 23.7 inch?
Thanks a lot!

**Comment by zdaxie** [comment]
So basically the problem is raised because of the Product ID of this new LG ultrafine 4k 23.7 inch is 0x9A63 instead of 0x9A40 in the code of this repo.
Change it and rebuild it will certainly solve this issue.

**Comment by 24fpsDaVinci** [comment]
thanks man, great job on this
